spring:
  # Mysql ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jspStudy
    username: root
    password: root

  # JSP??
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Mybatis ??
mybatis:
  # mapper location - ?? ? xml ??? ?????.
  mapper-locations: classpath:mappers/*/*.xml
  # column name to camel case - ?? ?? ???? CamelCase? ?? ??? ???.
  configuration:
    map-underscore-to-camel-case: true

